### ISSUE TITLE
能否在正文部分加颜色

### ISSUE THREAD

**Issue by junyixu** [MacroUniverse/PhysWiki#3]
比如说用 `\emp{}` 
`\renewcommand\emshape{\color{red}}`

觉得人眼还是挺喜欢看彩色的东西的

**Comment by MacroUniverse** [comment]
你是说把现在的粗体 textbf 替换成有颜色的吗？

**Comment by junyixu** [comment]
重要名词可以换成蓝色粗体，然后需要强调的地方可以用红色．

只是个不成熟的小建议

**Comment by MacroUniverse** [comment]
暂时先不考虑吧
